finalproject/config/routes.rb
Rails.application.routes.draw do
  
  root 'sessions#new'

  get 'signup' => 'users#new'

  resources :jobs
  resources :breaches
  resources :users do
    resources :operatives, :shallow => true
  end

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  get 'logout' => 'sessions#destroy'

end

finalproject/app/models/user.rb
class User < ActiveRecord::Base
  has_many :breaches
  has_many :targets, :through => :breaches
  has_many :inverse_breaches, :class_name => "Breaches", :foreign_key => "target_id"
  has_many :inverse_targets, :through => :inverse_breaches, :source => :user

  has_many :operatives

  has_secure_password
  validates_confirmation_of :password
  validates :name, uniqueness: true

  validates :firewall, numericality: { :greater_than_or_equal_to => 0 }
  validates :zeroday, numericality: { :greater_than_or_equal_to => 0 }
  validates :honeypot, numericality: { :greater_than_or_equal_to => 0 }
  validates :o_contract, numericality: { :greater_than_or_equal_to => 0 }

  def check_for_breaches
    breaches_by_user = Breach.where(user_id: self.id)

    breaches_by_user.each do |breach|
      #check for new breaches where payout is true
      if breach.reward_collected != true && breach.breached != false
        breacher = User.find(breach.user_id) 
        cash_taken = User.find(breach.target_id).cash - breach.cash_stolen
        cash_earned = breacher.cash + breach.cash_stolen

        #transact cash
        User.find(breach.target_id).update(cash: cash_taken)
        breacher.update(cash: cash_earned)

        #flag this breach as paid out
        update_zeroday = breacher.zeroday - 1
        breacher.update(zeroday: update_zeroday)
        breach.update(reward_collected: true)
      end
    end
    #find where cur_user was target of breaches
=begin
    breaches_by_enemies = Breach.where(target_id: self.id)
  
    breaches_by_enemies.each do |breach|
      #check for new breaches where payout is true
      if breach.reward_collected != true && breach.breached != false
        enemy_breacher = User.find(breach.user_id) 
        cash_taken = User.find(breach.target_id).cash - breach.cash_stolen
        cash_earned = enemy_breacher.cash + breach.cash_stolen

        #transact cash
        self.update(cash: cash_taken)
        enemy_breacher.update(cash: cash_earned)

        #flag this breach as paid out
        enemy_breacher.update(zeroday: update_zeroday)
        breach.update(reward_collected: true)
      end
    end
=end
  end

  end

finalproject/app/controllers/users_controller.rb
class UsersController < ApplicationController
  layout "new_user", only: [:new, :create]
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_filter :authorize, :except => [:new, :create]


  # GET /users
  # GET /users.json
  def index
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @operatives = current_user.operatives 
    @operatives.each do |operative|
      operative.check_job_status
    end
    @new_operative = current_user.operatives.new
    @operative = current_user.operatives.new
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    

    if @user.save
      for i in 1..4
        @new_operative = @user.operatives.new
        @new_operative.starting_operative(@user.id)
      end
      #item_params = {:user_id => @user.id}
      #@item = Item.new(item_params)
      #@item.save
      redirect_to @user, notice: 'Account was successfully created.'
    else
      render :new 
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    if @user.update(user_params)
      redirect_to @user, notice: 'Transaction was successfull.'
    else
      redirect_to @user, notice: 'WARNING: Transaction could not be completed.'
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'Account was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :password, :password_confirmation, :firewall, :active_firewall, :honeypot, :active_honeypot)
    end
end

finalproject/app/helpers/users_helper.rb
module UsersHelper
   def self.steal(breach)
    self.cash = current_user.cash + breach.cash_stolen
  end 
end

finalproject/app/views/users/_activate_firewall.html.erb
<%= form_for(current_user) do |f| %>
  <% if current_user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(current_user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% current_user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="hidden-field">
    <%= f.hidden_field(:firewall, :value => (current_user.firewall - 5)) %>
    <%= f.hidden_field(:active_firewall, :value => (current_user.active_firewall + 1)) %>
  </div> 
  <div class="actions">
    <%= f.submit "Activate Firewall(-5 Firewall)" %>
  </div>
<% end %>

finalproject/app/views/users/_activate_honeypot.html.erb
<%= form_for(current_user) do |f| %>
  <% if current_user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(current_user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% current_user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="hidden-field">
    <%= f.hidden_field(:honeypot, :value => (current_user.honeypot - 4)) %>
    <%= f.hidden_field(:active_honeypot, :value => (current_user.active_honeypot + 1)) %>
  </div> 
  <div class="actions">
    <%= f.submit "Activate Honeypot(-4 Honeypot)" %>
  </div>
<% end %>

finalproject/app/views/users/_activate_operative.html.erb
<%= form_for(current_user) do |f| %>
  <% if current_user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(current_user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% current_user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  
<% end %>

  <div class="actions">
    <%= button_to"Hire Operative(-1 Contact)",  {:controller => "operative", :action => "create" , :method => :post} %>
  </div>

finalproject/app/views/users/_claim_stolen_assets.html.erb
<%= form_for([current_user, @breach]) do |f| %>
  <% if current_user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(current_user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% current_user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="hidden-field">
    <%= f.hidden_field(:cash, :value => (current_user.cash + @breach.cash_stolen)) %>
  </div> 
  <div class="actions">
    <%= f.submit "Activate Firewall(-1 Firewall)" %>
  </div>
<% end %>

finalproject/app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :new_password  %><br>
    <%= f.text_field :password %>
  </div>
 
  <div class="actions">
    <%= f.submit "Change Password" %>
  </div>
<% end %>

finalproject/app/views/users/_signup_form.html.erb
<p id="notice"><%= notice %></p>
<h1>Signup Page</h1>
<div class="signup-wrapper">
  <%= form_for(@user) do |f| %>
    <div>
      <%= f.label :Username %>
      <%= f.text_field :name %>
    </div>
  
    <div>
      <%= f.label :password %>
      <%= f.password_field :password %>
    </div>

    <div>
      <%= f.label :password_confirmation, "Password Confirmation" %>
      <%= f.password_field :password_confirmation %>
    </div>

    <%= f.submit "Create Account" %>
<% end %>
</div>

finalproject/app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

finalproject/app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Password</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.password %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

finalproject/app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'signup_form' %>

<%= link_to 'Back', users_path %>

finalproject/app/views/users/show.html.erb
<h1><%= current_user.name %>'s assets</h1>
<table>
  <caption class="operative-table-head">Operatives</caption>
  <tr>
    <td>Name</td>
    <td>Status</td>
    <td>Skill</td>
    <td>Job</td>
  </tr>
  <% @operatives.each  do |cur_operative|%>
    <tr>
      <% if !cur_operative.new_record? %>
      <td><%= cur_operative.name %></td>
      <td><%= cur_operative.status %></td>
      <td><%= cur_operative.skill %></td>

      <% if cur_operative.status != "deployed" %>
        <td><%= link_to "New Job",  edit_operative_path(cur_operative), :method => :get %></td>
      <% else %>
        <td><%= cur_operative.job_id %></td>
      <% end %>
      
      <% if cur_operative.status == "injured" or cur_operative.status == "mia" %>
        <td><%= link_to 'Dispose', cur_operative, method: :delete,data: {confirm: "Sever all ties and destroy all records of #{cur_operative.name}?" }  %></td>
      <% end %>
      
      <% if cur_operative.status != "injured" and cur_operative.status != "mia" %>
        <td><%= link_to 'Fire', cur_operative, method: :delete,data: {confirm: "Release #{cur_operative.name} from contract?" } %></td>
      <% end %>
    </tr> 
    <% end %>
  <% end %> 
</table>

<table>
  <caption class="item-table-head">Items</caption>
  <tr>
    <td>Zero-days</td>
    <td>Operative Contracts</td>
    <td>Firewalls</td>
    <td>Honeypots</td>
  </tr>
    <tr>
      <td><%= current_user.zeroday %></td>
      <td><%= current_user.o_contract%></td>
      <td><%= current_user.firewall %></td>
      <td><%= current_user.honeypot %></td>
    </tr>
</table>

<table>
  <caption class="defense-table-head">Active Defenses</caption>
  <tr>
    <td>Firewalls</td>
    <td>Honeypots</td>
  </tr>
    <tr>
      <td><%= current_user.active_firewall %></td>
      <td><%= current_user.active_honeypot %></td>
    </tr>
</table>

<% if current_user.firewall  > 0 %>
  <%= render "activate_firewall" %>
<% end %>
<% if current_user.o_contract  > 0 %>
  <%= render "operatives/activate_operative" %>
<% end %>
<% if current_user.honeypot  > 0 %>
  <%= render "activate_honeypot" %>
<% end %>