finalproject/config/routes.rb
Rails.application.routes.draw do
  
  root 'sessions#new'

  get 'signup' => 'users#new'

  resources :jobs
  resources :breaches
  resources :users do
    resources :operatives, :shallow => true
  end

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  get 'logout' => 'sessions#destroy'

end

finalproject/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Finalproject</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<strong><%= current_user.name %> <%=number_to_currency(current_user.cash, precision: 0) %></strong> 
<strong> <%= Time.now.in_time_zone("UTC").strftime("%m/%d %H%M%Z") %> </strong>
<%= link_to 'log out', logout_path %> | 
<%= link_to 'edit account', edit_user_path(current_user) %>
<p id="notice"><%= notice %></p>
<ul class="nav">
  <li><%= link_to 'Main', user_path(current_user) %></li>
  <li><%= link_to 'Breaches', breaches_path %></li>
</ul>

<%= yield %>

</body>
</html>

finalproject/app/views/layouts/new_user.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Finalproject</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

finalproject/app/views/layouts/sessions.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Finalproject</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>