ratings/config/routes.rb
Rails.application.routes.draw do

resources :professors do
  resources :ratings, shallow: true
end

root 'professors#index'

end

ratings/app/models/professor.rb
class Professor < ActiveRecord::Base

  has_many :ratings, dependent: :destroy

  def name
    first + ' ' + last
  end

end

ratings/app/models/rating.rb
class Rating < ActiveRecord::Base
  belongs_to :professor
end

ratings/app/controllers/professors_controller.rb
class ProfessorsController < ApplicationController

  before_action :set_professor, only: [:show,:edit, :update, :destroy]  

  #GET /professors
  def index
    @professors = Professor.all
  end

  #GET /professors/1
  def show
  end

  #GET /professors/new
  def new
    @professor = Professor.new
  end

  #GET /professors/1/edit
  def edit
  end

  #GET /professors
  def create
    @professor = Professor.new(professor_params)
  
  if @professor.save
    redirect_to @professor, notice: "Professor was successfully updated."
  else
    render :new
  end

  end

  #PATCH/PUT /professors/1
  def update
    if @professor.update(professor_params)
      redirect_to @professor, notice: "Professor was updated."
    else
      render :edit
    end
  end

  #DELETE /professors/1
  def destroy
    @professor.destroy
    redirect_to professors_url
  end

  private
    #callbacks share common setup or constraints between actions
    def set_professor
      @professor = Professor.find(params[:id])
    end

    #whitelist the following params
    def professor_params
      params.require(:professor).permit(:first, :last, :university)
    end

end

ratings/app/controllers/ratings_controller.rb
#This controller does not have a show function
#because ratings are shown by professor (1 prof to many ratings)

class RatingsController < ApplicationController

  before_action :set_rating, only: [:edit, :update, :destroy]

  #GET /professors/:professor_id/ratings
  def index
    # index is now all the ratings for a single professor (not all the ratings)
    # the URL will contain the id of the current professor (:professor_id)
    # use the :professor_id parameter to find all the ratings
    @professor = Professor.find params[:professor_id]
    # the has_many function called in app/models/professor.rb created the 
    # function "ratings" which will return an array of all the ratings 
    # with the professor foreign key matching @professor
    @ratings = @professor.ratings
  end 
 
  #GET /professors/:professor_id/ratings/new
  def new
    #find the professor_id in the professors table
    @professor = Professor.find params[:professor_id] 
    #create a new rating object in the ratings table with
    #the previously found professor_id
    @rating = @professor.ratings.new
  end
  
  #GET /ratings/1/edit
  def edit
    #edit routes not nested because we know our professor's foreign key
  end

  #POST /professors/:professor_id/ratings
  def create
    #find professor_id again
    @professor = Professor.find params[:professor_id]
    #grab the users rating and put it in the corresponding
    #professor's ratings using the professor_id
    @rating = @professor.ratings.new(rating_params)

    if @rating.save
      redirect_to professor_ratings_url(@professor),  notice: "Rating was successfully created."
    else
      render :new
    end
  end

  #PATCH/PUT /ratings/1
  def update
    if @ratings.update(rating_params)
      redirect_to professor_ratings_url(@rating.professor), notice: "Rating was updated."
    end
  end

  #DELETE /ratings/1
  def destroy
    @rating.destroy
    redirect_to professor_ratings_url(@rating.professor), notice: "Rating was destroyed."
  end

  private
    def set_rating
      @rating = Rating.find(params[:id])
    end
  
    def rating_params
      params.require(:rating).permit(:course, :comment, :rating)
    end

end

ratings/app/views/ratings/_form.html.erb
<%= form_for([@professor, @rating]) do |f| %>
  <% if @rating.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@rating.errors.count, "error") %> prohibited this rating from being saved:</h2>

      <ul>
      <% @rating.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :course %><br>
    <%= f.text_field :course %>
  </div>
  <div class="field">
    <%= f.label :comment %><br>
    <%= f.text_field :comment %>
  </div>
  <div class="field">
    <%= f.label :rating %><br>
    <%= f.number_field :rating %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

ratings/app/views/ratings/edit.html.erb
<h1>Edit rating for <%= @rating.professor.name %> </h1>

<%= link_to 'Back', professor_ratings_path(@rating.professor) %>

<%= render 'form' %>

ratings/app/views/ratings/index.html.erb
<!-- the following calls the name() function in the Professor model -->
<h1><%= @professor.name %>'s Ratings </h1>

<table>
  <thead>
    <tr>
      <th>Course</th>
      <th>Comment</th>
      <th>Rating</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ratings.each do |rating| %>
      <tr>
        <td><%= rating.course %></td>
        <td><%= rating.comment %></td>
        <td><%= rating.rating %></td>
        <td><%= link_to 'Edit', edit_rating_path(rating) %></td>
        <td><%= link_to 'Destroy', rating, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Rating', new_professor_rating_path %> |
<%= link_to "Back to #{@professor.name}'s page", professor_path(@professor) %>

ratings/app/views/ratings/new.html.erb
<h1>New rating for <%= @professor.name %> </h1>

<%= link_to 'Back', professor_ratings_path %>

<%= render 'form' %>